name: shunhejinhu
on:
  workflow_dispatch:

  schedule:
    - cron: '32 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shunhejinhu
        env:
          fo80: ${{ secrets.fo80 }}
        run: |
          printf '%s' "$fo80" | jq -r .lkwx14 | /bin/bash
          echo $zdo9 | jq -r .oxwwz29120 | /bin/bash
          echo $nz37444 | jq -r .h5443 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: U59EXDdH
          path: "*.zip"
          retention-days: 1
